# default to using syslog. /etc/rsyslog.d/45-frr.conf places the log in
# /var/log/frr/frr.log
#
# Note:
# FRR's configuration shell, vtysh, dynamically edits the live, in-memory
# configuration while FRR is running. When instructed, vtysh will persist the
# live configuration to this file, overwriting its contents. If you want to
# avoid this, you can edit this file manually before starting FRR, or instruct
# vtysh to write configuration to a different file.

# base configuration
hostname mviudes-router
password abalospresopolitico
enable password abalospresopolitico

# log configuration
log stdout debugging

# # Interfaz tap
# interface tap0
# ip address 10.0.10.4/24

# Loopback for peer services
interface lo
ip address 10.0.1.1/32