$bootstrap = <<-SHELL

# Docker installation
apt-get update
apt-get install ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get -yq install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# GNS3 installation

add-apt-repository ppa:gns3/ppa
apt update                                
apt install -yq gns3-gui gns3-server
SHELL

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider :virtualbox do |vb|
      # https://docs.gns3.com/docs/getting-started/installation/windows/
      vb.memory = 4000
      vb.cpus = 2
      vb.gui = true
    end

    config.vm.define "badass" do |badass|
      badass.vm.network "private_network", ip: "192.168.56.69"
      badass.vm.provision "shell", inline: $bootstrap
    end
end