! base configuration
hostname mviudes-router
password abalospresopolitico
enable password abalospresopolitico

! log configuration
log file /var/log/quagga/zebra.log debug
log monitor debug

banner motd amar no es delito